### ISSUE TITLE
Thanks and new papers

### ISSUE THREAD

**Issue by araonblake** [Strivin0311/long-llms-learning#1]
Thanks a lot for the survey, very helpful for me to get started with the literature! There are recent relevant papers I read about but not included in the paper: https://arxiv.org/abs/2305.19370, https://arxiv.org/abs/2310.08560, https://arxiv.org/abs/2310.01889. 

It might be useful to add a note about best ways to contribute to this repo such as via pull request.

**Comment by Strivin0311** [comment]
Thank you for taking the time to read my survey paper and for your helpful contributions!
I will certainly consider incorporating the papers you mentioned into either the repository or the updated survey, since it's still in its draft version yet.
I wish you the very best in your ongoing research endeavors!




黄云鹏_南京大学
***@***.***







                       
Original Email
                       
                     

Sender:"Aaron Blake"< ***@***.*** &gt;;

Sent Time:2023/11/23 9:08

To:"Strivin0311/long-llms-learning"< ***@***.*** &gt;;

Cc recipient:"Subscribed"< ***@***.*** &gt;;

Subject:[Strivin0311/long-llms-learning] Thanks and new papers (Issue #1)




 
Thanks a lot for the survey, very helpful for me to get started with the literature! There are recent relevant papers I read about but not included in the paper: https://arxiv.org/abs/2305.19370, https://arxiv.org/abs/2310.08560, https://arxiv.org/abs/2310.01889.
 
It might be useful to add a note about best ways to contribute to this repo such as via pull request.
